### PR TITLE
Capistrano 3 support: internal PR for discussion

### PR DESCRIPTION
**Pull request by ento**

### CODE REVIEW

**Comment by ento** [comment]
This PR has served its purpose, closing

**Comment by SamGerber-zz** [comment]
I think we need to point the monolith somewhere else before we can kill this branch:
https://github.com/NoRedInk/NoRedInk/blob/2245d22c34a8d55427f68b6e1b59279e96560ee5/Gemfile#L380

https://noredink.slack.com/archives/C933X6H6G/p1517881401000096

**Comment by michaelglass** [comment]
I released a new gem yesterday and master now uses it

**Comment by michaelglass** [comment]
but: shouldn't have deleted this branch! was an oversight

**Pull request closed without merging**
